apiVersion: v1
kind: ConfigMap
metadata:
  name: flowforge-config
  namespace: event-platform
data:
  postgres-host: postgres
  postgres-port: "5432"
  postgres-db: flowforge
  redis-host: redis
  redis-port: "6379"
  kafka-bootstrap-servers: flowforge-kafka-kafka-bootstrap:9092
  topic-requested: data.process.requested
  topic-retry: data.process.retry
  topic-dlq: data.process.dlq
  worker-consumer-group: data-worker-group
  worker-max-retry-count: "3"
