apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: data-worker-service
  namespace: event-platform
spec:
  scaleTargetRef:
    name: data-worker-service
  pollingInterval: 15
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: flowforge-kafka-kafka-bootstrap:9092
        consumerGroup: data-worker-group
        topic: data.process.requested
        lagThreshold: "100"
