global:
  namespace: event-platform

dataApiService:
  image:
    repository: flowforge-data-api-service
    tag: latest
    pullPolicy: IfNotPresent

dataWorkerService:
  image:
    repository: flowforge-data-worker-service
    tag: latest
    pullPolicy: IfNotPresent

ingress:
  host: flowforge.local
